[deploy]
    release_command = "npm run build"

[process]
    app = "node app.js"
    [[services]]
        http_checks = []
        internal_port = 8080
        processes = ["app"]
    

[build]
    [build.args]
        NODE_VERSION = "16.19.1"